name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # runs every 10 minutes
  workflow_dispatch:         # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render Backend
        run: curl -s https://ai-career-coach-backend-amp9.onrender.com/health
